version: '3'

networks:
    bdnet:
      ipam:
        config:
          - subnet: 10.100.0.0/24

services: 
    rating-service:
        build: ./Rating_Service/
        restart: always
        depends_on: 
            - mongodb
        networks:
            bdnet:
                ipv4_address: 10.100.0.4    

    communication-service-dhaka:
        build: ./Communication_Service/
        # ports: 
        #     - 5001:5001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.22
    
    ride-sharing-service-dhaka:
        build: ./Ride_Sharing_Service/
        restart: always
        depends_on: 
            - communication-service-dhaka
        environment: 
            - LOCATION=dhaka
        networks:
            bdnet:
                ipv4_address: 10.100.0.21

    nginx-dhaka:
        build: ./nginx/
        # ports: 
        #     - 7000:80
        depends_on: 
            - rating-service
            - ride-sharing-service-dhaka
        environment: 
            - RSS=ride-sharing-service-dhaka
            - RS=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.20

    communication-service-chittagong:
        build: ./Communication_Service/
        # ports: 
        #     - 5002:5001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.32
                
    ride-sharing-service-chittagong:
        build: ./Ride_Sharing_Service/
        restart: always
        depends_on: 
            - communication-service-chittagong
        environment: 
            - LOCATION=chittagong
        networks:
            bdnet:
                ipv4_address: 10.100.0.31
            
    nginx-chittagong:
        build: ./nginx/
        # ports: 
        #     - 7000:80
        depends_on: 
            - rating-service
            - ride-sharing-service-chittagong
        environment: 
            - RSS=ride-sharing-service-chittagong
            - RS=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.30

    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        volumes:
            - data:/data/db
        networks:
            bdnet:
                ipv4_address: 10.100.0.5
    
volumes:
    data: